### ISSUE TITLE
3.0.0-beta.0 - crypto.subtle is undefined

### ISSUE THREAD

**Issue by rntjr** [authts/react-oidc-context#1055]
I accidentally downloaded this version in my project and this error ended up occurring. I went back to version 2.3.1 and fixed the problem.

Apparently when it calls the signinRedirect() method, it returns this error in Firefox. In Chrome it just returns the undefined property, without informing the attribute.

![image](https://github.com/authts/react-oidc-context/assets/48002341/32710601-e1ff-4a79-b739-5b7862da3cfc)

stacktrace chrome:
```
"TypeError: Cannot read properties of undefined (reading 'digest')
    at e.generateCodeChallenge (http://localhost:8080/static/js/main.4de1d383.js:2:312436)
    at e.create (http://localhost:8080/static/js/main.4de1d383.js:2:337814)
    at e.create (http://localhost:8080/static/js/main.4de1d383.js:2:339326)
    at Ma.createSigninRequest (http://localhost:8080/static/js/main.4de1d383.js:2:343698)
    at async ui._signinStart (http://localhost:8080/static/js/main.4de1d383.js:2:368844)
    at async ui._signin (http://localhost:8080/static/js/main.4de1d383.js:2:368697)
    at async ui.signinSilent (http://localhost:8080/static/js/main.4de1d383.js:2:365877)
    at async Object.signinSilent (http://localhost:8080/static/js/main.4de1d383.js:2:374647)
    at async http://localhost:8080/static/js/main.4de1d383.js:2:635407"
```

oidcConfig

```typescript
import { AuthProviderProps } from 'react-oidc-context'
import { WebStorageStateStore } from 'oidc-client-ts'

export const oidcConfig: AuthProviderProps = {
  authority: `${process.env.REACT_APP_KEYCLOAK_URL}`,
  client_id: `${process.env.REACT_APP_KEYCLOAK_CLIENT_ID}`,
  redirect_uri: `${process.env.REACT_APP_KEYCLOAK_REDIRECT_URI}`,
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  onSigninCallback: (): void => {
    window.history.replaceState({}, document.title, window.location.pathname)
  },
  metadata: {
    issuer: `${process.env.REACT_APP_KEYCLOAK_URL}`,
    authorization_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/auth`,
    token_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/token`,
    introspection_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/token/introspect`,
    userinfo_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/userinfo`,
    end_session_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/logout`,
    jwks_uri: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/certs`,
    check_session_iframe: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/login-status-iframe.html`,
    registration_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/clients-registrations/openid-connect`,
    revocation_endpoint: `${process.env.REACT_APP_KEYCLOAK_URL}/protocol/openid-connect/revoke`,
  },
}

```

**Comment by pamapa** [comment]
Which version of Firefox and Chrome are you using on which OS?

**Comment by pamapa** [comment]
Ahh, are you using this library in a none secure way?

See https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto:
Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#browser_compatibility).

**Comment by pamapa** [comment]
Only localhost/127.0.0.0 is allowed to access `crypto.subtle` on non HTTPS, see official documentation linked above.

**Comment by pamapa** [comment]
[Fixed](https://github.com/authts/oidc-client-ts/issues/1299) in oidc-client-ts, by throwing an exception...
